### PR TITLE
Add new resources on the french page.

### PR DESCRIPTION
**Pull request by bzg**
Thanks for merging!

### CODE REVIEW

**Comment by mitio** [comment]
Great, thanks!

**Comment by mitio** [comment]
I just need to resolve the conflicts here. If you have a minute, you can try to redo the changes in this PR in a new one. This will speed things up for me.

**Comment by bzg** [comment]
Done.  You can merge now.  Thanks!

**Comment by mitio** [comment]
Okay, thanks again!

**Pull request merged**
