### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by acoll23**
Updating an old link

### CODE REVIEW

**Comment by mitio** [comment]
@acoll23 Thanks for updating this!

I think it's better to host the file in the repo, though, and not depend on another third-party service (such as Dropbox). Do you have the file? Can you put it in the repo and link to it? Do you think its licence would allow that?

**Comment by acoll23** [comment]
Hi,

I translated this file from the original in English. I sent this file to scratch.mit.edu and originally they put it in another location, but now they has put it in Dropbox.

If you think it's better, we can put the file in the repo. There isn't any problem with the license.

**Comment by mitio** [comment]
@acoll23 Let's put it in this repo and link to it.

Can you update the pull request with this change? You'll probably need to checkout the repo and branch `patch-1` locally to do this change. Let's also use a relative path to the file when linking to it.

**Comment by mitio** [comment]
@acoll23 will you have a chance to look into this?

**Comment by mitio** [comment]
Ping @acoll23 :)

**Comment by mitio** [comment]
Let's accept that, we can fix it later if needed.

**Pull request merged**
